services:
  db:
    image: mariadb:10.6
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
      - cartunez-network

  wordpress:
    image: wordpress:latest
    ports:
      - "8083:80"
    volumes:
      - ./src:/var/www/html
      - ./php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    restart: always
    depends_on:
      - db
    networks:
      - cartunez-network

networks:
  cartunez-network:
    driver: bridge

volumes:
  db_data:
